version: '3.8'
services:
  backend:
    build:
      context: ..
      dockerfile: ./Docker/Dockerfile
    restart: always
    depends_on:
      - db
    environment:
      - ASPNETCORE_URLS=http://+:5173
    ports:
      - 5173:5173