version: '3.8'
services:
  syncfusion-backend:
    build:
      context: ..
      dockerfile: ./Docker/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_URLS=http://+:5174
    ports:
      - 5174:5174